import { ALL_TOPICS } from './techTopics.js';

// One small sidebar per project (2026-09-27, direct instruction: "each
// project and all the pages related to such project have exactly the same
// menu... access to different projects should be managed in the top bar
// menus" -- replacing the earlier single giant basket-grouped tree, which
// made every project's page carry a sidebar listing every OTHER project
// too). Generated from techTopics.js's ALL_TOPICS, not hand-written once
// per project, so a topic added there needs no matching edit here.
//
// Each project's sidebar carries the project's own flagship hub page, then
// exactly 3 destinations -- Technical Analysis, Reference Tools (or
// Testbed), Specifications -- the same as sidebars-home.js's own
// per-project sidebars, real vs. link swapped depending on which plugin
// instance owns which page (a sidebar can only hold real docs from its OWN
// plugin instance; the other two destinations are `type: 'link'` here
// since their real docs live in the "home" instance). "All Projects"
// always leads back out to /tech's own Where We Stand chart, which links
// into every project's own destinations -- the site's real "switch
// project" surface now that this sidebar no longer lists every project
// itself.
const sidebars = {
  // General portal-wide reference material, not per-project -- unchanged
  // from the old single tutorialSidebar, just split out into its own named
  // sidebar now that per-project pages carry their own instead.
  resourcesSidebar: [
    { type: 'link', label: 'Overview', href: '/tech' },
    { type: 'html', value: 'Resources', className: 'sidebar-section-label', defaultStyle: false },
    'exchanges',
    'blueprints',
    'specifications',
    '3gpp-work-items',
  ],
};

ALL_TOPICS.forEach((topic) => {
  const slug = topic.techHref.replace('/tech/', '');
  const items = [
    { type: 'link', label: 'All Projects', href: '/tech#where-we-stand' },
    // The project's own flagship hub page (src/pages/tech/<slug>/index.js)
    // -- its own hero/cards page, distinct from "Technical Analysis" below,
    // which goes straight to the deep-dive doc instead (2026-09-27, direct
    // instruction: "Technical Analysis should go directly to overview...
    // the main hub of the project should be clickable with its own project
    // name").
    { type: 'link', label: topic.label, href: topic.techHref },
  ];

  items.push(
    topic.autogen
      ? {
          type: 'category',
          label: 'Technical Analysis',
          collapsed: false,
          ...(topic.techOverviewDoc ? { link: { type: 'doc', id: topic.techOverviewDoc } } : {}),
          items: [{ type: 'autogenerated', dirName: topic.autogen }],
        }
      : {
          type: 'link',
          label: 'Technical Analysis',
          href: topic.techOverviewDoc ? `/tech/${topic.techOverviewDoc}` : topic.techHref,
        }
  );

  if (topic.refTools) {
    items.push({
      type: 'link',
      label: topic.refTools.isTestbed ? 'Testbed' : 'Reference Tools',
      href: topic.refTools.href,
    });
  }

  if ((topic.standards || []).length === 1) {
    // A single Standards doc: a flat link, same as Reference Tools/Testbed
    // above -- no need for a collapsible category over one destination.
    // Docusaurus categories can only `link` to a doc in this SAME plugin
    // instance (Standards docs live in "home"), so a header link isn't
    // possible here the way sidebars-home.js's own Specifications category
    // gets one; a flat link sidesteps that limitation entirely for the
    // common single-doc case.
    items.push({
      type: 'link',
      label: 'Specifications',
      href: `/${topic.standards[0].doc}`,
    });
  } else if ((topic.standards || []).length > 1) {
    items.push({
      type: 'category',
      label: 'Specifications',
      // No header `link`: a category can only link to a doc in this same
      // plugin instance, and Standards docs live in "home" -- clicking the
      // header here just expands/collapses, same limitation Reference
      // Tools/Testbed would have if it were rendered as a category instead
      // of a flat link. Child labels drop the "Standards: " prefix each
      // one's own techTopics.js entry carries (used standalone elsewhere)
      // -- redundant once already nested under a "Specifications" heading.
      collapsed: false,
      items: topic.standards.map((s) => ({
        type: 'link',
        label: s.label.replace(/^Standards: /, ''),
        href: `/${s.doc}`,
      })),
    });
  }

  sidebars[`sidebar_${slug.replace(/-/g, '_')}`] = items;
});

export default sidebars;
