/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // The navbar no longer links back to the bare /tech hub once you're
    // inside this section (its own nav item is a constant link to /tech
    // itself, same on every route) — this is the way back to it.
    { type: 'link', label: 'Overview', href: '/tech' },
    // intro.md removed (2026-07-20): fully redundant with the /tech hub's own
    // topic grid, apart from its per-topic Kanban execution-plan links — those
    // are slated to move onto /tech's own topic cards later instead.
    // Feedback and Requirements and Liaison Statements moved to /standards
    // (docs/home) — see sidebars-home.js. public-call merged into
    // /events/public-call. Glossary and 3GPP Work Items moved to /standards
    // then back here (2026-07-19): general portal-wide reference material,
    // not Feedback/Requirements/LS, so they belong under Explainers &
    // Profiles rather than Standards.
    { type: 'html', value: 'Resources', className: 'sidebar-section-label', defaultStyle: false },
    'videos',
    'videos-external',
    'glossary',
    '3gpp-work-items',

    {
      type: 'html',
      value: 'Media Streaming &amp; Broadcast',
      className: 'sidebar-section-label',
      defaultStyle: false,
    },
    {
      type: 'category',
      label: '5G Media Streaming (5GMS)',
      link: { type: 'doc', id: '5gms' },
      items: [{ type: 'autogenerated', dirName: '5gms' }, 'standards/5gms'],
    },
    {
      type: 'category',
      label: '5G Broadcast - TV, Radio and Emergency Alerts',
      link: { type: 'doc', id: '5g-broadcast' },
      items: [
        { type: 'autogenerated', dirName: '5g-broadcast' },
        'standards/5g-broadcast',
        'standards/5g-broadcast-standards-evolution',
      ],
    },
    {
      type: 'category',
      label: '5G Multicast Broadcast Services (MBS)',
      link: { type: 'doc', id: '5g-mbs' },
      items: [{ type: 'autogenerated', dirName: '5g-mbs' }, 'standards/5g-mbs'],
    },
    {
      type: 'category',
      label: 'DVB-I Services over 5G Systems',
      link: { type: 'doc', id: 'dvb-i/dvb-i-5g' },
      items: ['standards/dvb-i'],
    },
    {
      type: 'category',
      label: 'Multimedia Delivery Protocols',
      link: { type: 'doc', id: 'multimedia/multimedia-content-delivery' },
      items: ['standards/multimedia'],
    },

    {
      type: 'html',
      value: 'Network &amp; Connectivity',
      className: 'sidebar-section-label',
      defaultStyle: false,
    },
    {
      type: 'category',
      label: 'Network APIs',
      link: { type: 'doc', id: 'network-apis' },
      items: [{ type: 'autogenerated', dirName: 'network-apis' }, 'standards/network-apis'],
    },
    {
      type: 'category',
      label: 'Non-Terrestrial Networks',
      link: { type: 'doc', id: 'ntn' },
      items: [{ type: 'autogenerated', dirName: 'ntn' }, 'standards/ntn'],
    },
    {
      type: 'category',
      label: 'Non-Public Networks',
      link: { type: 'doc', id: 'npn' },
      items: ['standards/npn'],
    },
    {
      type: 'category',
      label: 'Real-Time Media Communication (RTC)',
      link: { type: 'doc', id: 'rtc/rtc' },
      items: ['standards/rtc'],
    },
    {
      type: 'category',
      label: 'Time-Sensitive Communications',
      link: { type: 'doc', id: 'tsc/tsc' },
      items: ['standards/tsc'],
    },
    {
      type: 'category',
      label: 'UE Data Collection',
      link: { type: 'doc', id: 'data-collection/data-collection-event-exposure' },
      items: ['standards/data-collection'],
    },

    {
      type: 'html',
      value: 'Immersive &amp; Emerging Media',
      className: 'sidebar-section-label',
      defaultStyle: false,
    },
    {
      type: 'category',
      // Matches xr.md's own title exactly (this category is only ever
      // XR/MPEG-I Scene Description content, unlike the Volumetric category
      // below which deliberately bundles two distinct child topics).
      label: 'XR and MPEG-I Scene Description',
      link: { type: 'doc', id: 'xr' },
      items: [{ type: 'autogenerated', dirName: 'xr' }, 'standards/xr'],
    },
    {
      type: 'category',
      label: 'Volumetric & Beyond-2D Video',
      link: { type: 'doc', id: 'volumetric' },
      items: [
        { type: 'autogenerated', dirName: 'volumetric' },
        'standards/v3c',
        'standards/beyond-2d',
      ],
    },
    {
      type: 'category',
      label: 'Avatar Communications',
      link: { type: 'doc', id: 'avatar-communications' },
      items: ['standards/avatar'],
    },
    'standards/ai-ml',
    {
      type: 'category',
      label: 'Towards 6G Media',
      link: { type: 'doc', id: '6g' },
      items: ['standards/6g'],
    },
  ],
};

export default sidebars;
