import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import matter from 'gray-matter';

// Node-only helper (fs access; never imported by browser-bundled code --
// see techTopics.js's own comment on why it avoids fs) used by both
// sidebars-home.js and sidebars-tech.js to build a manually-specified
// sidebar category from a docs folder that lives in the OTHER Docusaurus
// plugin instance than the sidebar currently being generated.
//
// A Docusaurus sidebar can only build a *real*, `type: 'autogenerated'`
// category from docs in its OWN plugin instance (see both sidebar files'
// own comments on this). This reproduces just enough of that resolver --
// frontmatter label + position, `_category_.json` label + position,
// recursion into subfolders -- to give the "foreign" pillar the exact
// same expandable shape. Every child is `type: 'link'` (a plain href),
// never `type: 'doc'`, since a plain link needs no same-instance doc
// resolution and works regardless of which instance is rendering it.
//
// Direct instruction (2026-09-28): "I want this to be managed per
// project, e.g. all what is 5gms will get the same lateral menu no
// matter where pages are" -- replacing the flat-link fallback that made
// the "foreign" pillar look thinner than the native one.
const ROOT_DIR = path.dirname(fileURLToPath(import.meta.url));

function prettify(name) {
  return name
    .replace(/\.(mdx?|jsx?|tsx?)$/, '')
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function readCategoryMeta(dirAbs) {
  const file = path.join(dirAbs, '_category_.json');
  if (!fs.existsSync(file)) return {};
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch {
    return {};
  }
}

// Scans `relDir` (relative to the repo root, e.g. 'docs/tech/5g-mbs') and
// returns a Docusaurus sidebar items array (`type: 'link'` / `type:
// 'category'`), sorted the way Docusaurus's own autogenerated resolver
// sorts them: explicit `sidebar_position`/`position` ascending first,
// then alphabetical by label as the tiebreak for everything else.
//
// `routeBasePathPrefix` is the scanned instance's own routeBasePath
// (e.g. '/tech' for docs/tech, '' for docs/home) -- confirmed live
// (docs/tech/volumetric/beyond-2d.mdx's `slug: /beyond-2d` resolves to
// /tech/beyond-2d, not the bare value) that a `slug` frontmatter override
// is relative to it, the same as a path-derived href already is.
export function deriveLinkItems(relDir, urlPrefix, routeBasePathPrefix = '') {
  const dirAbs = path.join(ROOT_DIR, relDir);
  if (!fs.existsSync(dirAbs)) return [];
  const entries = fs.readdirSync(dirAbs, { withFileTypes: true });
  const items = [];

  for (const entry of entries) {
    if (entry.name.startsWith('_') || entry.name.startsWith('.')) continue;
    const abs = path.join(dirAbs, entry.name);

    if (entry.isDirectory()) {
      const meta = readCategoryMeta(abs);
      const children = deriveLinkItems(
        path.join(relDir, entry.name),
        `${urlPrefix}/${entry.name}`,
        routeBasePathPrefix
      );
      if (children.length === 0) continue;
      items.push({
        type: 'category',
        label: meta.label || prettify(entry.name),
        collapsed: meta.collapsed ?? true,
        items: children,
        __position: meta.position ?? Infinity,
      });
      continue;
    }

    if (!/\.mdx?$/.test(entry.name)) continue;
    const raw = fs.readFileSync(abs, 'utf8');
    const { data } = matter(raw);
    const slugified = entry.name.replace(/\.mdx?$/, '');
    // `slug` frontmatter, when set, is relative to the plugin instance's
    // own routeBasePath -- always starts with '/' by this codebase's own
    // convention (checked: docs/home/standards/5g-mbs-standards-evolution.md
    // uses exactly this form) -- so it composes with `urlPrefix`'s own
    // instance root the same way a path-derived href does.
    const href = data.slug
      ? `${routeBasePathPrefix}${data.slug}`
      : slugified === 'index'
        ? urlPrefix
        : `${urlPrefix}/${slugified}`;
    items.push({
      type: 'link',
      label: data.sidebar_label || data.title || prettify(entry.name),
      href,
      __position: data.sidebar_position ?? Infinity,
    });
  }

  items.sort((a, b) => a.__position - b.__position || a.label.localeCompare(b.label));
  return items.map((item) => {
    const { __position, ...rest } = item;
    void __position;
    return rest;
  });
}
