import { TECH_GROUPS, RESEARCH_EXTRA_LINKS } from './techTopics.js';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // The navbar no longer links back to the bare /tech hub once you're
    // inside this section (its own nav item is a constant link to /tech
    // itself, same on every route) — this is the way back to it.
    { type: 'link', label: 'Overview', href: '/tech' },
    // intro.md removed (2026-07-20): fully redundant with the /tech hub's own
    // topic grid, apart from its per-topic Kanban execution-plan links — those
    // are slated to move onto /tech's own topic cards later instead.
    // Feedback and Requirements and Liaison Statements moved to /standards
    // (docs/home) — see sidebars-home.js. public-call merged into
    // /events/public-call. Glossary and 3GPP Work Items moved to /standards
    // then back here (2026-07-19): general portal-wide reference material,
    // not Feedback/Requirements/LS, so they belong under Explainers &
    // Profiles rather than Standards.
    //
    // Per-project "what specs does this implement" pages (2026-08-11): moved
    // from docs/tech/standards/*.md (served at /tech/standards/<project>) to
    // docs/home/standards/*.md (served at /standards/<project>), alongside
    // the existing feedback/requirements/LS pages, at the site owner's
    // request — despite the naming overlap with that different "5G-MAG as
    // SDO contributor" material, a deliberate tradeoff. Moving plugin
    // instance (tech -> home) was required: a docs slug starting with "/" is
    // NOT actually absolute across plugin instances in this Docusaurus
    // version — plugin-content-docs always joins routeBasePath + slug
    // (see node_modules/@docusaurus/plugin-content-docs/lib/docs.js's
    // `normalizeUrl([versionMetadata.path, docSlug])`), so a doc living
    // under the "tech" plugin (routeBasePath: 'tech') can only ever resolve
    // under /tech/*, no matter what its slug says. The items below are now
    // explicit `link` entries (not doc-id strings) since these docs no
    // longer belong to this plugin's own doc collection.
    { type: 'html', value: 'Resources', className: 'sidebar-section-label', defaultStyle: false },
    'exchanges',
    'blueprints',
    'specifications',
    'glossary',
    '3gpp-work-items',

    // Groups, topics and their Standards pages all come from techTopics.js, so
    // this sidebar and the Standards-side sidebar in sidebars-home.js cannot
    // drift apart. Here the analysis pages are real docs and the Standards
    // pages are links, because those live in the other plugin instance.
    ...TECH_GROUPS.flatMap((group) => [
      {
        type: 'html',
        value: group.label,
        className: 'sidebar-section-label',
        defaultStyle: false,
      },
      ...group.topics.map((topic) => ({
        type: 'category',
        label: topic.label,
        link: { type: 'doc', id: topic.techDoc },
        items: [
          ...(topic.autogen ? [{ type: 'autogenerated', dirName: topic.autogen }] : []),
          ...(topic.standards || []).map((s) => ({
            type: 'link',
            label: s.label,
            href: `/${s.doc}`,
          })),
        ],
      })),
      ...(group.label === 'Research Topics'
        ? RESEARCH_EXTRA_LINKS.map((l) => ({ type: 'link', label: l.label, href: l.href }))
        : []),
    ]),
  ],
};

export default sidebars;
