import { TECH_GROUPS, RESEARCH_EXTRA_LINKS } from './techTopics.js';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // /about and /membership are now full custom Hub pages (src/pages/about,
  // src/pages/membership) with their own PageNav bar — 'about' and
  // 'membership' docs removed accordingly. about-structure/partnerships/
  // contact are likewise deliberately absent from every sidebar array here:
  // they're shallow docs (no children of their own) that duplicated the
  // /about SectionNav pill-bar with a redundant lateral sidebar — same
  // reasoning as the standards/developer docs further down this file. Each
  // now relies solely on its SectionNav pill-bar (src/data/sectionNav.js).

  // Everything below used to live under docs-developer (routeBasePath
  // 'developer') and was moved to root-level paths (/dashboard,
  // /applications, /reference-tools, /testbeds) as part of the
  // 2026-07-18 domain consolidation. Each keeps its own named sidebar
  // (rather than one merged docs/home sidebar) so a visitor on /about
  // doesn't see Reference Tools/Testbeds/etc. mixed in, and vice versa.
  // Each "Overview" link below points back to that sidebar's own hub page
  // (/applications, /reference-tools, /testbeds — each a plain src/pages
  // React page, not part of this plugin).
  //
  // communitySidebar removed entirely (2026-07-18): how-to-use,
  // guidelines-contributors and Contributors moved back to /developer/*,
  // and public-call now lives at /public-call (docs/home/public-call.mdx).
  // /community itself was retired as a standalone page (2026-07-18): its
  // content was a subset of /developer's own "Join the Community" section,
  // so it now redirects there (see docusaurus.config.js's static
  // `redirects` list) instead of carrying any content or sidebar of its own.
  //
  // The docs-developer plugin instance itself was retired (2026-07-18):
  // its last 3 docs (how-to-use, guidelines-contributors, license) moved
  // into docs/home/developer/*.md with explicit slug overrides, the same
  // pattern used just above for /contact, /partnerships, /structure.

  // applications/index itself is deliberately NOT part of this sidebar (no
  // `link` on the outer category below) — it's now a full custom Hub page
  // (src/pages/applications/index.js) with its own PageNav bar.
  applicationsSidebar: [
    { type: 'link', label: 'Overview', href: '/applications' },
    {
      type: 'category',
      label: 'Applications',
      items: [
        {
          type: 'category',
          label: '5G Media Streaming (5GMS)',
          link: { type: 'doc', id: 'applications/streaming' },
          items: [{ type: 'autogenerated', dirName: 'applications/streaming' }],
        },
        'applications/5g-broadcast',
        'applications/volumetric',
        'applications/network-apis',
      ],
    },
  ],

  // reference-tools/index itself is deliberately NOT part of this sidebar
  // — it's now a full custom Hub page (src/pages/reference-tools/index.js)
  // with its own PageNav bar. The 14 project trees below stay in this
  // sidebar since each is genuinely nested (releases/repositories/scope/
  // tutorials sub-pages).
  //
  // 2026-07-23: dropped the "Overview" link (it duplicated the "Reference
  // Tools" pill already in the SectionNav bar above). Grouping was also
  // switched from the old use-case buckets (Media Streaming & Broadcast /
  // Network & Connectivity / Immersive & Emerging Media) to mirror
  // reference-tools/index.js's own CATEGORIES: each tool is grouped by the
  // standards body it implements, same order as the hub page.
  // Also dropped the outer "Reference Tools" wrapping category (it had no
  // `link` and, once non-collapsible, rendered as inert text) and restored
  // per-project collapse/collapsed — collapsed by default, so the sidebar
  // isn't 14 projects' worth of Scope/Resources/Tutorials all open at once.
  referenceToolsSidebar: [
    {
      type: 'html',
      value: '3GPP Implementations',
      className: 'sidebar-section-label',
      defaultStyle: false,
    },
    {
      type: 'category',
      label: '3GPP RAN and Core Platforms',
      link: { type: 'doc', id: 'reference-tools/3gpp-platforms/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/3gpp-platforms' }],
    },
    {
      type: 'category',
      label: '5G Broadcast - Emergency Alerts',
      link: { type: 'doc', id: 'reference-tools/emergency-alerts/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/emergency-alerts' }],
    },
    {
      type: 'category',
      label: '5G Broadcast - TV and Radio Services',
      link: { type: 'doc', id: 'reference-tools/5g-broadcast/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/5g-broadcast' }],
    },
    {
      type: 'category',
      label: '5G Core Service Consumers',
      link: { type: 'doc', id: 'reference-tools/5g-core/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/5g-core' }],
    },
    {
      type: 'category',
      label: '5G Media Streaming (5GMS)',
      link: { type: 'doc', id: 'reference-tools/5gms/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/5gms' }],
    },
    {
      type: 'category',
      label: '5G Multicast Broadcast Services (MBS)',
      link: { type: 'doc', id: 'reference-tools/5g-mbs/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/5g-mbs' }],
    },
    {
      type: 'category',
      label: 'DVB-I Services over 5G Systems',
      link: { type: 'doc', id: 'reference-tools/dvb-i/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/dvb-i' }],
    },
    {
      type: 'category',
      label: 'UE Data Collection, Reporting and Event Exposure',
      link: { type: 'doc', id: 'reference-tools/data-collection/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/data-collection' }],
    },

    {
      type: 'html',
      value: 'MPEG Implementation',
      className: 'sidebar-section-label',
      defaultStyle: false,
    },
    {
      type: 'category',
      label: 'Conversational Avatar Communication with MPEG ARF',
      link: { type: 'doc', id: 'reference-tools/avatar/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/avatar' }],
    },
    {
      type: 'category',
      label: 'MPEG V3C Immersive Platform',
      link: { type: 'doc', id: 'reference-tools/v3c/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/v3c' }],
    },
    {
      type: 'category',
      label: 'XR/3D Scenes with MPEG-I Scene Description',
      link: { type: 'doc', id: 'reference-tools/xr/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/xr' }],
    },

    {
      type: 'html',
      value: 'IETF Implementations',
      className: 'sidebar-section-label',
      defaultStyle: false,
    },
    {
      type: 'category',
      label: 'Multimedia Delivery Protocols',
      link: { type: 'doc', id: 'reference-tools/multimedia/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/multimedia' }],
    },

    {
      type: 'html',
      value: 'CAMARA Project Implementations',
      className: 'sidebar-section-label',
      defaultStyle: false,
    },
    {
      type: 'category',
      label: 'CAMARA Connectivity Quality Management APIs',
      link: { type: 'doc', id: 'reference-tools/network-apis/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/network-apis' }],
    },

    {
      type: 'html',
      value: 'Shared Tools',
      className: 'sidebar-section-label',
      defaultStyle: false,
    },
    {
      type: 'category',
      label: 'Common Tools',
      link: { type: 'doc', id: 'reference-tools/common-tools/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference-tools/common-tools' }],
    },
  ],

  // testbeds/index itself is deliberately NOT part of this sidebar (no
  // `link` on the outer category below) — it's a shallow hub page that now
  // carries its own PageNav bar instead (see src/pages/testbeds/index.js,
  // a custom React page, not a docs/home doc).
  // The three actual project trees below stay in this sidebar since each is
  // genuinely nested (releases/repositories/scope/tutorials sub-pages).
  testbedsSidebar: [
    { type: 'link', label: 'Overview', href: '/testbeds' },
    {
      type: 'category',
      label: 'Testbeds',
      items: [
        {
          type: 'category',
          label: 'AI Traffic Characterization',
          link: { type: 'doc', id: 'testbeds/6g-testbed/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'testbeds/6g-testbed' }],
        },
        {
          type: 'category',
          label: 'AI/ML Evaluation Framework',
          link: { type: 'doc', id: 'testbeds/ai-ml/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'testbeds/ai-ml' }],
        },
        {
          type: 'category',
          label: 'Beyond 2D Evaluation Framework',
          link: { type: 'doc', id: 'testbeds/beyond-2d/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'testbeds/beyond-2d' }],
        },
      ],
    },
  ],

  // docs/home/standards/ holds two distinct groups that share a URL prefix:
  // the 18 per-project specification pages (moved here from
  // docs/tech/standards/ on 2026-08-11 so they serve at
  // /standards/<project>) and the three "5G-MAG as SDO contributor" pages
  // (requirements, ls, 3gpp-issue-tracking).
  //
  // 2026-08-12: they now carry a real sidebar again. The move to this
  // plugin instance silently dropped one — under /tech/standards/* they
  // were nested items in sidebars-tech.js's capability-area categories, so
  // they inherited the whole Tech sidebar; here they were in no sidebar
  // array at all, which is how 21 pages ended up with no lateral
  // navigation. The grouping below deliberately mirrors sidebars-tech.js
  // (and /tech's own CATEGORIES) so the specification pages keep reading
  // as the same content family they are linked from, with the contributor
  // pages kept visibly separate at the end.
  // The per-topic Standards pages are part of the Tech hub, not a section of
  // their own: they list the specifications behind a topic's analysis and
  // reference tools, and are only served under /standards/<topic> URLs.
  //
  // So this renders the SAME topic tree as the Tech sidebar, from the same
  // definition in techTopics.js. A reader on /standards/5g-mbs sees the Tech
  // menu with the 5G MBS topic open and its Standards page highlighted, not a
  // separate Standards menu. The mirroring is required because a sidebar can
  // only hold docs from its own plugin instance: here the Standards pages are
  // real docs (so they highlight) and the Tech analysis pages are links.
  standardsSidebar: [
    { type: 'link', label: 'Overview', href: '/tech' },

    {
      type: 'html',
      value: 'Resources',
      className: 'sidebar-section-label',
      defaultStyle: false,
    },
    { type: 'link', label: 'Technology Exchanges', href: '/tech/exchanges' },
    { type: 'link', label: 'Implementation Blueprints', href: '/tech/blueprints' },
    { type: 'link', label: 'Glossary', href: '/tech/glossary' },
    { type: 'link', label: '3GPP Work Items', href: '/tech/3gpp-work-items' },

    ...TECH_GROUPS.flatMap((group) => [
      {
        type: 'html',
        value: group.label,
        className: 'sidebar-section-label',
        defaultStyle: false,
      },
      ...group.topics.map((topic) => ({
        type: 'category',
        label: topic.label,
        collapsed: false,
        items: [
          ...(topic.techDoc ? [{ type: 'link', label: 'Analysis', href: topic.techHref }] : []),
          ...(topic.standards || []).map((s) => s.doc),
        ],
      })),
      ...(group.label === 'Research Topics'
        ? RESEARCH_EXTRA_LINKS.map((l) => ({ type: 'link', label: l.label, href: l.href }))
        : []),
    ]),
  ],

  // The three contributor pages behind the /standards hub (5G-MAG as an SDO
  // participant) are a different thing from the per-topic specification pages
  // above, and keep their own short sidebar.
  feedbackSidebar: [
    { type: 'link', label: 'Overview', href: '/standards' },
    'standards/requirements',
    'standards/ls',
    'standards/3gpp-issue-tracking',
  ],

  // The /community cluster is small but genuinely nested (three sub-pages
  // under the index), and its SectionNav pill-bar only carries a single
  // "Community" pill for the whole section — so before this sidebar
  // existed, contributing/release-process/using-this-documentation were
  // reachable only from the index page itself.
  communitySidebar: [
    'community/index',
    'community/using-this-documentation',
    'community/contributing',
    'community/release-process',
  ],

  // docs/home/developer/*.md (how-to-use, guidelines-contributors, license)
  // are deliberately absent from every sidebar array: they carry explicit
  // slug overrides to live at /developer/* (folded in from the old
  // docs-developer plugin instance, 2026-07-18) and are linked from the
  // /developer SectionNav pill-bar instead of a doc sidebar. The same
  // applies to the standalone leaf pages (/contact, /structure,
  // /partnerships, /subscribe, /license, /early-access, /videos, /podcast
  // and the event pages): each is a single page with no siblings to
  // navigate between, so a lateral sidebar would have nothing to list.
  // docs/home/workshops/* (22 archive write-ups) also stay out: the
  // /workshops archive index is their listing, and they carry no ordering
  // metadata, so an autogenerated sidebar would order them arbitrarily.
};

export default sidebars;
