/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // /about and /membership are now full custom Hub pages (src/pages/about,
  // src/pages/membership) with their own PageNav bar — 'about' and
  // 'membership' docs removed accordingly. about-structure/partnerships/
  // contact are likewise deliberately absent from every sidebar array here:
  // they're shallow docs (no children of their own) that duplicated the
  // /about SectionNav pill-bar with a redundant lateral sidebar — same
  // reasoning as the standards/developer docs further down this file. Each
  // now relies solely on its SectionNav pill-bar (src/data/sectionNav.js).

  // Everything below used to live under docs-developer (routeBasePath
  // 'developer') and was moved to root-level paths (/dashboard,
  // /applications, /reference-tools, /testbeds) as part of the
  // 2026-07-18 domain consolidation. Each keeps its own named sidebar
  // (rather than one merged docs/home sidebar) so a visitor on /about
  // doesn't see Reference Tools/Testbeds/etc. mixed in, and vice versa.
  // Each "Overview" link below points back to that sidebar's own hub page
  // (/applications, /reference-tools, /testbeds — each a plain src/pages
  // React page, not part of this plugin).
  //
  // communitySidebar removed entirely (2026-07-18): how-to-use,
  // guidelines-contributors and Contributors moved back to /developer/*,
  // and public-call merged into /events/public-call (see docs/home/events/).
  // /community itself was retired as a standalone page (2026-07-18): its
  // content was a subset of /developer's own "Join the Community" section,
  // so it now redirects there (see docusaurus.config.js's static
  // `redirects` list) instead of carrying any content or sidebar of its own.
  //
  // The docs-developer plugin instance itself was retired (2026-07-18):
  // its last 3 docs (how-to-use, guidelines-contributors, license) moved
  // into docs/home/developer/*.md with explicit slug overrides, the same
  // pattern used just above for /contact, /partnerships, /structure.

  // applications/index itself is deliberately NOT part of this sidebar (no
  // `link` on the outer category below) — it's now a full custom Hub page
  // (src/pages/applications/index.js) with its own PageNav bar.
  applicationsSidebar: [
    { type: 'link', label: 'Overview', href: '/applications' },
    {
      type: 'category',
      label: 'Applications',
      items: [
        {
          type: 'category',
          label: '5G Media Streaming (5GMS)',
          link: { type: 'doc', id: 'applications/streaming' },
          items: [{ type: 'autogenerated', dirName: 'applications/streaming' }],
        },
        'applications/5g-broadcast',
        'applications/multicast-broadcast',
        'applications/xr',
        'applications/volumetric',
        'applications/network-apis',
      ],
    },
  ],

  // reference-tools/index itself is deliberately NOT part of this sidebar
  // (no `link` on the outer category below) — it's now a full custom Hub
  // page (src/pages/reference-tools/index.js) with its own PageNav bar.
  // The 15 project trees below stay in this sidebar since each is
  // genuinely nested (releases/repositories/scope/tutorials sub-pages).
  referenceToolsSidebar: [
    { type: 'link', label: 'Overview', href: '/reference-tools' },
    {
      type: 'category',
      label: 'Reference Tools',
      items: [
        {
          type: 'html',
          value: 'Media Streaming &amp; Broadcast',
          className: 'sidebar-section-label',
          defaultStyle: false,
        },
        {
          type: 'category',
          label: '5G Media Streaming (5GMS)',
          link: { type: 'doc', id: 'reference-tools/5gms/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/5gms' }],
        },
        {
          type: 'category',
          label: '5G Broadcast - TV and Radio',
          link: { type: 'doc', id: 'reference-tools/5g-broadcast/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/5g-broadcast' }],
        },
        {
          type: 'category',
          label: '5G Broadcast - Emergency Alerts',
          link: { type: 'doc', id: 'reference-tools/emergency-alerts/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/emergency-alerts' }],
        },
        {
          type: 'category',
          label: '5G Multicast Broadcast Services (MBS)',
          link: { type: 'doc', id: 'reference-tools/5g-mbs/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/5g-mbs' }],
        },
        {
          type: 'category',
          label: 'DVB-I Services over 5G Systems',
          link: { type: 'doc', id: 'reference-tools/dvb-i/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/dvb-i' }],
        },
        {
          type: 'category',
          label: 'Multimedia Delivery Protocols',
          link: { type: 'doc', id: 'reference-tools/multimedia/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/multimedia' }],
        },

        {
          type: 'html',
          value: 'Network &amp; Connectivity',
          className: 'sidebar-section-label',
          defaultStyle: false,
        },
        {
          type: 'category',
          label: '3GPP RAN and Core Platforms',
          link: { type: 'doc', id: 'reference-tools/3gpp-platforms/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/3gpp-platforms' }],
        },
        {
          type: 'category',
          label: '5G Core Service Consumers',
          link: { type: 'doc', id: 'reference-tools/5g-core/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/5g-core' }],
        },
        {
          type: 'category',
          label: 'Network APIs',
          link: { type: 'doc', id: 'reference-tools/network-apis/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/network-apis' }],
        },
        {
          type: 'category',
          label: 'UE Data Collection, Reporting and Event Exposure',
          link: { type: 'doc', id: 'reference-tools/data-collection/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/data-collection' }],
        },

        {
          type: 'html',
          value: 'Immersive &amp; Emerging Media',
          className: 'sidebar-section-label',
          defaultStyle: false,
        },
        {
          type: 'category',
          label: 'XR and MPEG-I Scene Description',
          link: { type: 'doc', id: 'reference-tools/xr/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/xr' }],
        },
        {
          type: 'category',
          label: 'Avatar Communication with MPEG ARF',
          link: { type: 'doc', id: 'reference-tools/avatar/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/avatar' }],
        },
        {
          type: 'category',
          label: 'V3C Immersive Platform',
          link: { type: 'doc', id: 'reference-tools/v3c/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/v3c' }],
        },

        {
          type: 'html',
          value: 'Shared Tools',
          className: 'sidebar-section-label',
          defaultStyle: false,
        },
        {
          type: 'category',
          label: 'Common Tools',
          link: { type: 'doc', id: 'reference-tools/common-tools/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/common-tools' }],
        },
        {
          type: 'category',
          label: 'External Tools',
          link: { type: 'doc', id: 'reference-tools/external-tools/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'reference-tools/external-tools' }],
        },
      ],
    },
  ],

  // testbeds/index itself is deliberately NOT part of this sidebar (no
  // `link` on the outer category below) — it's a shallow hub page that now
  // carries its own PageNav bar instead (see src/pages/testbeds/index.js,
  // a custom React page, not a docs/home doc).
  // The three actual project trees below stay in this sidebar since each is
  // genuinely nested (releases/repositories/scope/tutorials sub-pages).
  testbedsSidebar: [
    { type: 'link', label: 'Overview', href: '/testbeds' },
    {
      type: 'category',
      label: 'Testbeds',
      items: [
        {
          type: 'category',
          label: 'AI Traffic Characterization',
          link: { type: 'doc', id: 'testbeds/6g-testbed/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'testbeds/6g-testbed' }],
        },
        {
          type: 'category',
          label: 'AI/ML Evaluation Framework',
          link: { type: 'doc', id: 'testbeds/ai-ml/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'testbeds/ai-ml' }],
        },
        {
          type: 'category',
          label: 'Beyond 2D Evaluation Framework',
          link: { type: 'doc', id: 'testbeds/beyond-2d/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'testbeds/beyond-2d' }],
        },
      ],
    },
  ],

  // Feedback and Requirements moved from docs/tech (/tech/standards/feedback)
  // to root (/standards) — see sidebars-tech.js. 3 flat docs
  // (3gpp-issue-tracking, ls, methodology; glossary and 3gpp-work-items
  // moved on to docs/tech — 2026-07-19 — as general reference material
  // rather than Feedback/Requirements/LS, see sidebars-tech.js), not
  // nested enough to warrant a lateral sidebar of their own; each page
  // carries a SectionNav pill-bar instead (see src/data/sectionNav.js and
  // docs/home/standards/*.mdx) and they are deliberately absent from every
  // sidebar array here.
  //
  // docs/home/developer/*.md (how-to-use, guidelines-contributors, license)
  // are likewise deliberately absent from every sidebar array: they carry
  // explicit slug overrides to live at /developer/* (folded in from the old
  // docs-developer plugin instance, 2026-07-18) and are linked from the
  // /developer SectionNav pill-bar instead of a doc sidebar.
};

export default sidebars;
