import { ALL_TOPICS } from './techTopics.js';
import taxonomyData from './src/data/taxonomy.json';

// One small sidebar per project (2026-09-27, direct instruction: "each
// project and all the pages related to such project have exactly the same
// menu... access to different projects should be managed in the top bar
// menus" -- replacing the earlier separate standardsSidebar/
// referenceToolsSidebar, each of which listed every project in its own
// family, with no cross-links between families). Generated from
// techTopics.js's ALL_TOPICS, mirroring sidebars-tech.js's own per-project
// generation -- same destinations, same order, real vs. link swapped
// here since Standards and Reference Tools docs both live in THIS plugin
// instance ("home") while Technical Analysis lives in the separate "tech"
// instance (a sidebar can only hold real docs from its own instance).
function refToolsFolder(href) {
  // '/reference-tools/5gms' -> 'reference-tools/5gms', '/testbeds/6g-testbed'
  // -> 'testbeds/6g-testbed' -- both live under docs/home/, so both can be
  // real autogenerated categories here, unlike on the Tech side.
  return href.replace(/^\//, '');
}

const projectSidebars = {};
ALL_TOPICS.forEach((topic) => {
  const slug = topic.techHref.replace('/tech/', '');
  const items = [
    { type: 'link', label: 'All Projects', href: '/tech#where-we-stand' },
    // The project's own flagship hub page, distinct from "Technical
    // Analysis" below (2026-09-27, direct instruction -- see
    // sidebars-tech.js's own matching comment for the full reasoning).
    { type: 'link', label: topic.label, href: topic.techHref },
  ];

  items.push({
    type: 'link',
    label: 'Technical Analysis',
    href: topic.techOverviewDoc ? `/tech/${topic.techOverviewDoc}` : topic.techHref,
  });

  if (topic.refTools) {
    const folder = refToolsFolder(topic.refTools.href);
    items.push({
      type: 'category',
      label: topic.refTools.isTestbed ? 'Testbed' : 'Reference Tools',
      link: { type: 'doc', id: `${folder}/index` },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: folder }],
    });
  }

  if ((topic.standards || []).length > 0) {
    items.push({
      type: 'category',
      label: 'Specifications',
      // Links straight to the topic's own primary Standards doc (2026-09-27,
      // direct instruction: clicking the category header was a bare
      // expand/collapse toggle, landing nowhere) -- same pattern the
      // Reference Tools/Testbed category above already uses. A topic with
      // more than one Standards doc (e.g. 5G MBS's own standards-evolution
      // companion) still lists the rest as real children below.
      link: { type: 'doc', id: topic.standards[0].doc },
      collapsed: false,
      items: topic.standards.map((s) => s.doc),
    });
  }

  projectSidebars[`sidebar_${slug.replace(/-/g, '_')}`] = items;
});

// Reference-Tools-only projects with no tech_url of their own (real
// destinations, documented `excludedReason` in taxonomy.json -- not a gap)
// -- same residual set the old referenceToolsSidebar's "Shared
// Infrastructure" group covered, now one small sidebar each instead of one
// shared group, for the same "identical shape per project" reasoning as
// everything else here. Derived from taxonomy.json, not hand-listed, so a
// new doc_url'd-but-tech_url-less project picks this up automatically.
const sharedInfraSlugs = taxonomyData.projects
  .filter((p) => p.doc_url && p.doc_url.startsWith('/reference-tools/') && !p.tech_url)
  .map((p) => p.doc_url.replace(/^\/reference-tools\//, '').replace(/\/$/, ''));

sharedInfraSlugs.forEach((slug) => {
  projectSidebars[`sidebar_${slug.replace(/-/g, '_')}`] = [
    { type: 'link', label: 'All Reference Tools', href: '/reference-tools' },
    {
      type: 'category',
      label: 'Reference Tools',
      link: { type: 'doc', id: `reference-tools/${slug}/index` },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: `reference-tools/${slug}` }],
    },
  ];
});

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // /about and /membership are now full custom Hub pages (src/pages/about,
  // src/pages/membership) with their own PageNav bar — 'about' and
  // 'membership' docs removed accordingly. about-structure/partnerships/
  // contact are likewise deliberately absent from every sidebar array here:
  // they're shallow docs (no children of their own) that duplicated the
  // /about SectionNav pill-bar with a redundant lateral sidebar — same
  // reasoning as the standards/developer docs further down this file. Each
  // now relies solely on its SectionNav pill-bar (src/data/sectionNav.js).

  // showcase/index itself is deliberately NOT part of this sidebar (no
  // `link` on the outer category below) — it's now a full custom Hub page
  // (src/pages/showcase/index.js) with its own PageNav bar. Route renamed
  // from /applications to /showcase (2026-09-23); this sidebar's own key
  // renamed to match so it doesn't read stale next to the route it serves.
  // 2026-09-27: flattened (dropped the outer "Showcases" wrapping category,
  // and renamed "Overview" to "All Showcases") to match the shape/wording
  // the new per-project sidebars use ("All Projects" + flat items, no extra
  // nesting level) -- a site-wide consistency pass found this one sidebar
  // still one level deeper and differently worded than everything else.
  showcaseSidebar: [
    { type: 'link', label: 'All Showcases', href: '/showcase' },
    {
      type: 'category',
      label: '5G Media Streaming (5GMS)',
      link: { type: 'doc', id: 'showcase/streaming' },
      items: [{ type: 'autogenerated', dirName: 'showcase/streaming' }],
    },
    {
      type: 'category',
      label: '5G Broadcast for TV, Radio and Emergency Alerts',
      link: { type: 'doc', id: 'showcase/5g-broadcast' },
      items: [{ type: 'autogenerated', dirName: 'showcase/5g-broadcast' }],
    },
    'showcase/volumetric',
    'showcase/network-apis',
  ],

  // testbeds/index itself is deliberately NOT part of this sidebar (no
  // `link` on the outer category below) — it's a shallow hub page that now
  // carries its own PageNav bar instead (see src/pages/testbeds/index.js,
  // a custom React page, not a docs/home doc).
  //
  // 2026-09-27: 6g-testbed and ai-ml dropped from here -- both now have a
  // real techTopics.js entry (6g, ai-ml) and so get their own per-project
  // sidebar above (its "Testbed" category autogenerates this exact same
  // folder), and a doc can only belong to one named sidebar. beyond-2d has
  // no techTopics.js entry of its own (it's a nested page under v3c's own
  // Tech analysis instead, via its own slug override), so it stays here,
  // the only real testbed left with no other sidebar claiming it.
  // 2026-09-27: flattened and relabelled, same reasoning as showcaseSidebar
  // just above.
  testbedsSidebar: [
    { type: 'link', label: 'All Testbeds', href: '/testbeds' },
    {
      type: 'category',
      label: 'Beyond 2D Evaluation Framework',
      link: { type: 'doc', id: 'testbeds/beyond-2d/index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'testbeds/beyond-2d' }],
    },
  ],

  // The three contributor pages behind the /standards hub (5G-MAG as an SDO
  // participant: requirements.mdx, ls.mdx, 3gpp-issue-tracking.mdx) used to
  // carry their own short sidebar here (feedbackSidebar). Removed
  // (2026-09-26, direct instruction: "all the pages under standardization...
  // need to look like /surveys... there is no need for the lateral menu in
  // this case") now that every page under the Standardisation SectionNav
  // group (src/data/sectionNav.js) already carries that pill bar for
  // cross-page navigation -- a lateral sidebar duplicated it. None of these
  // three docs are referenced in any sidebar array below, so (same mechanism
  // as /contact, /workshops) they render with no lateral sidebar; each still
  // has `hide_table_of_contents: true` in its own frontmatter to drop the
  // right-hand ToC too, matching the plain-page look of /surveys.

  // The /community cluster is small but genuinely nested (two real sub-pages
  // under the index), and its SectionNav pill-bar only carries a single
  // "Developer Community" pill for the whole section — so before this
  // sidebar existed, release-process and using-this-documentation were
  // reachable only from the index page itself.
  //
  // `contributing` (2026-09-26, direct instruction, "the page for
  // contributing has disappeared, put it under the developer community
  // page"): its own URL stays exactly `/contributing` -- unchanged,
  // deliberately kept flat since contributing.mdx moved out of this cluster
  // on 2026-09-10, same as public-call.mdx before it, and no redirect is
  // needed since nothing about the route changed. Only its SIDEBAR
  // membership changed: this array is what puts a doc "under" a section in
  // Docusaurus (sidebar membership, not URL nesting), and adding it here is
  // what surfaces it as a sibling of Using this Documentation/Release
  // Process again, after the Software Accelerator top bar's own separate
  // "Contributing" pill was removed per an earlier, unrelated instruction --
  // this restores the same discoverability through a different, real
  // mechanism (the lateral sidebar) instead of reverting that pill removal.
  // Same order as the Getting Started list on /community's own page, so the
  // sidebar and the page content read as the same sequence.
  communitySidebar: [
    'community/index',
    'community/using-this-documentation',
    'contributing',
    'community/release-process',
  ],

  // Per-project sidebars (Standards + Reference Tools/Testbed docs), one
  // per techTopics.js topic plus the Reference-Tools-only "Shared
  // Infrastructure" projects -- see projectSidebars' own construction above.
  ...projectSidebars,

  // docs/home/developer/exchanges.mdx (the one file left in that folder --
  // this comment used to also name how-to-use.md and
  // guidelines-contributors.md, both since removed from the repo entirely,
  // not just from this list) carries an explicit slug override to live at
  // /developer/exchanges (folded in from the old docs-developer plugin
  // instance, 2026-07-18) and is linked from the /developer SectionNav
  // pill-bar instead of a doc sidebar. The same applies to the standalone
  // leaf pages with no siblings to navigate between: /contact, /structure,
  // /partnerships, /subscribe, /privacy, /license, /early-access, /videos,
  // /podcast, /magazine, /public-call, the event pages (mwc, ibc, fmt,
  // 5g-broadcast-plugfest), and the event date pages under docs/home/events/.
  // docs/home/workshops/* (22 archive write-ups) also stay out: the
  // /workshops archive index is their listing, and they carry no ordering
  // metadata, so an autogenerated sidebar would order them arbitrarily.
  // Confirmed complete by a site-wide sidebar-coverage audit (2026-09-27).
};

export default sidebars;
