import { BASKETS } from './src/data/baskets.js';
import taxonomyData from './src/data/taxonomy.json';

// One definition of the Tech hub's topic tree, rendered by BOTH sidebars.
//
// The per-topic Standards pages belong to the Tech hub: they list the
// specifications a topic's analysis and reference tools are built against. They
// are only served under /standards/<topic> URLs. So they must appear inside the
// Tech topic menu, nested under their own topic, rather than in a separate menu
// of their own.
//
// That cannot be expressed in one sidebar file, because a Docusaurus sidebar can
// only contain docs from its own plugin instance, and the Tech analysis pages
// (docs/tech, routeBasePath 'tech') and the Standards pages (docs/home,
// routeBasePath '') live in different ones. Each side therefore renders the tree
// from here, holding its own docs as real entries and the other side's as links:
//
//   sidebars-tech.js  -> analysis pages are docs, Standards pages are links
//   sidebars-home.js  -> Standards pages are docs, analysis pages are links
//
// Both render the same groups, the same topics and the same order, so a reader
// sees one Tech menu either way and the current page highlights correctly.
//
// GROUPING is derived from src/data/taxonomy.json (the single taxonomy master)
// rather than hand-assigned here, so this file and the basket taxonomy can
// never drift apart -- a topic's basket is looked up by its own tech_url below.
// What is NOT derived is each topic's file wiring (techDoc id, techOverviewDoc
// -- the specific doc id sidebars link "Technical Analysis" straight to, only
// set where a single canonical overview.mdx really exists -- whether its
// folder is autogenerated, which Standards docs it links) -- taxonomy.json's
// tech_url doesn't encode the doc id (some are nested, e.g. RTC's file lives at
// rtc/rtc.md though its URL is /tech/rtc) or which Standards pages a topic
// carries, and this file can't safely compute that from the filesystem itself
// (it's imported by the browser-bundled Tech hub page as well as the
// Node-only sidebars, so no `fs` access here). Add a topic here, and it picks
// up its basket automatically from whichever project in taxonomy.json carries
// that tech_url; add a project to taxonomy.json with a NEW tech_url, and add
// its file-wiring entry here to make it a real menu item.
const ALL_TOPICS = [
  {
    // No techDoc (2026-09-25 pilot): /tech/5gms is now a hand-built plain
    // page (src/pages/tech/5gms/index.js), not a docs/tech/5gms.mdx doc --
    // raised directly ("I would like to use the regular page with hero
    // and so on... a normal page", confirmed: "no sidebar, true
    // standalone page"). Both sidebar builders already handle a
    // techDoc-less topic (sidebars-home.js's own Analysis link is already
    // conditional on `topic.techDoc`; sidebars-tech.js's category link
    // is conditional the same way now) -- the category still lists its
    // real sub-pages (autogen below), it just has no doc of its own to
    // link the category header itself to.
    label: '5G Media Streaming (5GMS)',
    techHref: '/tech/5gms',
    autogen: '5gms',
    techOverviewDoc: '5gms/overview',
    standards: [{ doc: 'standards/5gms', label: 'Standards: 5G Media Streaming (5GMS)' }],
  },
  {
    label: '5G Multicast Broadcast Services (MBS)',
    techHref: '/tech/5g-mbs',
    autogen: '5g-mbs',
    techOverviewDoc: '5g-mbs/overview-mbs',
    standards: [
      { doc: 'standards/5g-mbs', label: 'Standards: 5G Multicast Broadcast Services (MBS)' },
      {
        doc: 'standards/5g-mbs-standards-evolution',
        label: 'Standards: 5G MBS - Standards Evolution',
      },
    ],
  },
  {
    label: 'DVB-I Services over 5G Systems',
    techHref: '/tech/dvb-i',
    // Added 2026-09-27: this topic's own analysis doc
    // (docs/tech/dvb-i/analysis-dvb-i-over-5g-gaps.mdx) had no `autogen`
    // entry, unlike every other topic here -- a pre-existing gap that left
    // it with no lateral sidebar at all (found by a site-wide consistency
    // audit), not a deliberate choice.
    autogen: 'dvb-i',
    // Added 2026-09-28 (direct instruction: every project needs a real
    // landing page behind "Technical Analysis"): this topic has exactly
    // one analysis doc, so it IS the overview -- not one choice among
    // several, just wiring the header link to the content that already
    // exists.
    techOverviewDoc: 'dvb-i/analysis-dvb-i-over-5g-gaps',
    standards: [{ doc: 'standards/dvb-i', label: 'Standards: DVB-I Services over 5G Systems' }],
  },
  {
    label: 'Content Delivery Protocols',
    techHref: '/tech/content-delivery',
    autogen: 'content-delivery',
    techOverviewDoc: 'content-delivery/overview',
    standards: [
      { doc: 'standards/content-delivery', label: 'Standards: Content Delivery Protocols' },
      { doc: 'standards/cmmf', label: 'Standards: CMMF (Multisource Delivery)' },
    ],
  },
  {
    label: 'Non-Terrestrial Networks in 5G Systems',
    techHref: '/tech/ntn',
    autogen: 'ntn',
    standards: [{ doc: 'standards/ntn', label: 'Standards: Non-Terrestrial Networks in 5G Systems' }],
  },
  {
    label: 'Real-time Media Communication (RTC) Architecture',
    techHref: '/tech/rtc',
    autogen: 'rtc',
    techOverviewDoc: 'rtc/overview',
    standards: [{ doc: 'standards/rtc', label: 'Standards: Real-time Media Communication (RTC) Architecture' }],
  },
  {
    label: 'UE Data Collection, Reporting and Event Exposure',
    techHref: '/tech/data-collection',
    autogen: 'data-collection',
    techOverviewDoc: 'data-collection/overview',
    standards: [
      {
        doc: 'standards/data-collection',
        label: 'Standards: UE Data Collection, Reporting and Event Exposure',
      },
    ],
  },
  {
    // Used to cover two taxonomy.json projects (TV/Radio and Emergency
    // Alerts) sharing this one tech_url. Direct instruction (2026-09-27),
    // via the taxonomy-admin portal: Emergency Alerts was split out to its
    // own tech_url/standards_url and now has its own topic entry below --
    // see src/pages/tech/emergency-alerts/index.js's own comment for the
    // page-side half of this change.
    label: '5G Broadcast - TV and Radio Services',
    techHref: '/tech/5g-broadcast',
    autogen: '5g-broadcast',
    standards: [
      {
        doc: 'standards/5g-broadcast',
        label: 'Standards: 5G Broadcast - TV, Radio and Emergency Alerts',
      },
      {
        doc: 'standards/5g-broadcast-standards-evolution',
        label: 'Standards: 5G Broadcast - Standards Evolution',
      },
    ],
  },
  {
    label: '5G Broadcast - Emergency Alerts',
    techHref: '/tech/emergency-alerts',
    autogen: 'emergency-alerts',
    techOverviewDoc: 'emergency-alerts/overview',
    standards: [
      {
        doc: 'standards/emergency-alerts',
        label: 'Standards: 5G Broadcast - Emergency Alerts',
      },
    ],
  },
  {
    label: 'Conversational Avatar Communication with MPEG ARF',
    techHref: '/tech/avatar',
    autogen: 'avatar',
    techOverviewDoc: 'avatar/overview',
    standards: [
      { doc: 'standards/avatar', label: 'Standards: Conversational Avatar Communication with MPEG ARF' },
    ],
  },
  {
    // Also covers Beyond 2D (nested under this same directory, its own
    // Standards doc listed alongside V3C's).
    label: 'MPEG V3C Immersive Platform',
    techHref: '/tech/v3c',
    autogen: 'volumetric',
    standards: [
      { doc: 'standards/v3c', label: 'Standards: MPEG V3C Immersive Platform' },
      { doc: 'standards/beyond-2d', label: 'Standards: Beyond 2D Video' },
    ],
  },
  {
    label: 'XR/3D Scenes with MPEG-I Scene Description',
    techHref: '/tech/xr',
    autogen: 'xr',
    // Added 2026-09-28 (direct instruction: every project needs a real
    // landing page behind "Technical Analysis"): this topic has exactly
    // one analysis doc, so it IS the overview -- not one choice among
    // several, just wiring the header link to the content that already
    // exists.
    techOverviewDoc: 'xr/mpeg-i-scene-description',
    standards: [{ doc: 'standards/xr', label: 'Standards: XR/3D Scenes with MPEG-I Scene Description' }],
  },
  {
    label: 'Dynamic Mesh Coding',
    techHref: '/tech/vdmc',
    autogen: 'vdmc',
    techOverviewDoc: 'vdmc/overview',
    standards: [{ doc: 'standards/vdmc', label: 'Standards: Dynamic Mesh Coding' }],
  },
  {
    label: 'CAMARA Connectivity Quality Management APIs',
    techHref: '/tech/network-apis',
    autogen: 'network-apis',
    // Added 2026-09-28 (direct instruction: every project needs a real
    // landing page behind "Technical Analysis"): network-api-initiatives.md
    // is already explicitly written as this topic's entry point (title
    // "Network API Analysis", sidebar_position -1, introduces the whole
    // section) -- not a new page, just wiring the header link to it.
    techOverviewDoc: 'network-apis/network-api-initiatives',
    standards: [
      {
        doc: 'standards/network-apis',
        label: 'Standards: CAMARA Connectivity Quality Management APIs',
      },
    ],
  },
  {
    label: 'Non-Public Networks',
    techHref: '/tech/npn',
    autogen: 'npn',
    techOverviewDoc: 'npn/overview',
    standards: [{ doc: 'standards/npn', label: 'Standards: Non-Public Networks' }],
  },
  {
    label: 'Time-Sensitive Communications (TSC)',
    techHref: '/tech/tsc',
    autogen: 'tsc',
    techOverviewDoc: 'tsc/overview',
    standards: [{ doc: 'standards/tsc', label: 'Standards: Time-Sensitive Communications (TSC)' }],
  },
  {
    label: 'AI/ML Evaluation Framework',
    techHref: '/tech/ai-ml',
    autogen: 'ai-ml',
    techOverviewDoc: 'ai-ml/overview',
    standards: [{ doc: 'standards/ai-ml', label: 'Standards: AI/ML Evaluation Framework' }],
  },
  {
    label: 'Towards 6G Media',
    techHref: '/tech/6g',
    autogen: '6g',
    techOverviewDoc: '6g/overview',
    standards: [{ doc: 'standards/6g', label: 'Standards: Towards 6G Media' }],
  },
];

// techHref -> the project's own doc_url (Reference Tools, or a Testbed for
// the two testbeds-basket topics -- see BASKET_OVERRIDES below for why
// those two still have a Tech-menu presence at all), the same
// derive-don't-hand-list technique as basketForHref: a topic with no
// doc_url at all (true for none currently) simply gets no entry, and the
// per-project sidebar generators (sidebars-tech.js, sidebars-home.js) omit
// that destination rather than fabricate one.
const refToolsForHref = {};
taxonomyData.projects.forEach((p) => {
  if (p.tech_url && p.doc_url) {
    refToolsForHref[p.tech_url] = {
      href: p.doc_url.replace(/\/$/, ''),
      isTestbed: p.doc_url.startsWith('/testbeds/'),
    };
  }
});

// techHref -> basket key, from taxonomy.json's own projects -- the single
// place that decides which basket a topic belongs to.
//
// /tech/6g's own project (AI Traffic Characterization) carries basket
// "testbeds", since it is fundamentally a testbed, but its tech analysis
// has always sat under Towards 6G Media on this menu, not under a
// Testbeds group here (Testbeds has its own separate portal) -- it
// already gets its own entry below via RESEARCH_EXTRA_LINKS pointing at
// its testbed page, not this analysis page. AI/ML Evaluation Framework's
// own basket is "testbeds" too and gets the same treatment, for the same
// reason.
const BASKET_OVERRIDES = { '/tech/6g': 'towards-6g', '/tech/ai-ml': 'towards-6g' };
const basketForHref = {};
taxonomyData.projects.forEach((p) => {
  if (p.tech_url) basketForHref[p.tech_url] = p.basket;
});
Object.assign(basketForHref, BASKET_OVERRIDES);

// Attach each topic's own refTools destination (computed above) so every
// consumer of TECH_GROUPS/ALL_TOPICS sees it without a second lookup.
ALL_TOPICS.forEach((t) => {
  t.refTools = refToolsForHref[t.techHref] || null;
});

export const TECH_GROUPS = BASKETS.map((b) => ({
  key: b.key,
  label: b.title,
  icon: b.icon,
  topics: ALL_TOPICS.filter((t) => basketForHref[t.techHref] === b.key),
})).filter((g) => g.topics.length > 0);

// Exported flat (not grouped by basket) for the per-project sidebar
// generators in sidebars-tech.js/sidebars-home.js, which build one small
// sidebar per topic rather than one big basket-grouped tree.
export { ALL_TOPICS };

// Reachable from the Tech menu but not a Tech doc: the testbed has no Standards
// or Analysis page of its own, so it is a plain link in both renderings.
// Placed alongside Towards 6G since /tech/6g (its closest analysis
// neighbour) lives there -- see BASKET_OVERRIDES above.
export const RESEARCH_EXTRA_LINKS = [
  { label: 'AI Traffic Characterization', href: '/testbeds/6g-testbed' },
];
